# Make coffee at 5:50
- alias: Make early coffee at 5:50
  trigger:
    - platform: time
      at: "05:50"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_coffee_pot
    - delay: 00:10:00
    - service: switch.turn_off
      entity_id: switch.kitchen_coffee_pot

# Make coffee at 6:50
- alias: Make morning coffee at 6:50
  trigger:
    - platform: time
      at: "06:50"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_coffee_pot
    - delay: 00:10:00
    - service: switch.turn_off
      entity_id: switch.kitchen_coffee_pot

# Turn on window lights at 8:00
- alias: Turn on window lights at 8:00
  trigger:
    - platform: time
      at: "08:00"    
  action:
    - service: switch.turn_on
      entity_id: switch.livingroom_window_lights
    - service: switch.turn_on
      entity_id: switch.livingroom_charger