# Make coffee at 6:50
- alias: Make morning coffee at 6:50
  trigger:
    - platform: time
      at: "06:50"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_hue
          - light.kitchen
        brightness: 225
        color_temp: 100
        transition: 50
    - service: switch.turn_on
      entity_id: switch.kitchen_coffee_pot
    - delay: 00:05:00
    - service: switch.turn_off
      entity_id: switch.kitchen_coffee_pot
    - delay: 00:15:00
    - service: light.turn_off
      entity_id:
        - light.office_hue
        - light.kitchen

# Turn on window lights at 8:00
- alias: Turn on window lights at 8:00
  trigger:
    - platform: time
      at: "08:00"    
  action:
    - service: switch.turn_on
      entity_id: switch.livingroom_window_lights