# Hue Gen 1
- platform: hue
  host: 192.168.10.42

# Yeelights
- platform: yeelight
  devices:
    192.168.10.49:
      name: Kids Room
      transition: 1000
      use_music_mode: True
      # save_on_change: False
    192.168.10.40:
      name: Kitchen
      transition: 1000
      use_music_mode: True

# Sensor node LEDs
- platform: mqtt_json
  name: "SN1 LED"
  state_topic: "home/sensornode1"
  command_topic: "home/sensornode1/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0

# Tradfri
# ...