# Anton's room lamp
- platform: yeelight
  devices:
    192.168.10.48:
      name: Kids Room
      transition: 1000
      use_music_mode: True
      # save_on_change: False
    192.168.10.39:
      name: Kitchen
      transition: 1000
      use_music_mode: True