# Office side lamp - will be Anton's room lamp
- platform: yeelight
  devices:
    192.168.10.48:
      name: Office Side Lamp
      transition: 1000
      use_music_mode: True
      # save_on_change: False