# Hue Gen 1
- platform: hue
  host: !secret philips_hue_ip

# Yeelights
- platform: yeelight
  devices:
    192.168.10.78:
      name: Kids Room
      transition: 1000
      use_music_mode: True
      # save_on_change: False
    192.168.10.90:
      name: Kitchen
      transition: 1000
      use_music_mode: True

# Sensor node LEDs
- platform: mqtt_json
  name: "SN1 LED"
  state_topic: "home/sensornode1"
  command_topic: "home/sensornode1/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: "SN2 LED"
  state_topic: "home/sensornode2"
  command_topic: "home/sensornode2/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0

# ws2812b led strips on WeMos
- platform: mqtt_json
  name: "Office Strip"
  state_topic: "home/office/led_strip"
  command_topic: "home/office/led_strip/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter  
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle  
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: "Livingroom Strip"
  state_topic: "home/livingroom/led_strip"
  command_topic: "home/livingroom/led_strip/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter  
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle  
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0