# Weather sensor
- platform: yr
  monitored_conditions:
  - temperature
  - symbol
  - humidity

# Time and date sensor
- platform: time_date
  display_options:
    - 'date'
    - 'time'

# Net status
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

# Light amount sensor office
- platform: mqtt
  state_topic: 'home/office/light_sensor'
  name: 'Office brightness'
  unit_of_measurement: '%'
  value_template: '{{ value_json.brightness }}'

# Temperature sensor office
- platform: mqtt
  state_topic: 'home/office/temperature_sensor'
  name: 'Office temperature'
  unit_of_measurement: 'C'
  value_template: '{{ value_json.temperature }}'