# Click event
- alias: <FLIC:CLICK> Toggle coffee pot
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da732d5c
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.kitchen_outlet_2

# Hold event
- alias: <FLIC:HOLD> Turn off everything on first floor
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da732d5c
      click_type: hold
  action:
    - service: homeassistant.toggle
      entity_id: group.all_lights
    - service: switch.toggle
      entity_id: switch.livingroom_outlet_1
    - service: switch.toggle
      entity_id: switch.livingroom_tv_led_on_off