- alias: "Hello Mr. President!"
  trigger:
    platform: zone
    entity_id: device_tracker.georgi6p_gp
    zone: zone.mr_president
    # Event is either enter or leave
    event: enter  # or "leave"
  condition:
  - condition: time
    after: "16:00:00"
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Hello there, Mr. President!"

# Turn on Main PC when Georgi comes home
- alias: "Turn on main PC when Georgi comes home"
  trigger:
    platform: zone
    entity_id: device_tracker.georgi6p_gp
    zone: zone.home
    event: enter
  condition:
    - condition: time
      after: "16:00:00"
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: switch.main_computer
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Georgi has arrived home."

# Sofi comes home
- alias: "Sofi has arrived home"
  trigger:
    platform: zone
    entity_id: device_tracker.sofiip_sp
    zone: zone.home
    event: enter
  condition:
    - condition: time
      after: "15:00:00"
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Sofi has arrived home."

# Set TV backlights to demo when music is playing on Google Home
- alias: 'Playing music on Google Home turns on TV backlight demo'
  trigger:
    platform: state
    entity_id: media_player.living_room_home
    to: 'playing'
  condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ states.media_player.living_room_home.attributes.app_name == "Google Play Music" }}'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_ball_lights
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_music_jar
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_tv_led_demo
    - service: homeassistant.turn_on
      entity_id: light.livingroom_strip

# Set TV backlights to demo when music is playing on Google Home
- alias: 'Stopping music played on Google Home turn regular TV backlight'
  trigger:
    platform: state
    entity_id: media_player.living_room_home
    from: 'playing'
    # to: 'paused'
  condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.living_room_home
          state: 'paused'
        - condition: state
          entity_id: media_player.living_room_home
          state: 'idle'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_tv_led_teal
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_music_jar
    - service: homeassistant.turn_off
      entity_id: light.livingroom_strip

# Activate 'Movies' scene when Plex is playing
- alias: 'Playing Plex runs Movies scene'
  trigger:
    platform: state
    # This id should be the TV id
    entity_id: media_player.tv_ue49ku6675
    to: 'playing'
  action:
    - service: scene.turn_on
      entity_id: scene.movies