# Turn on lights at sunset
- alias: "Lights on 1.5 hours before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:30:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.living_room_hue
          - light.office_hue
        brightness: 225
        color_temp: 327
        transition: 2
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_window_lights
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_ball_lights
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.kids_room
        brightness: 225
        rgb_color: [255, 68, 0]
        transition: 2
    # - service: tts.google_say
    #   entity_id: media_player.living_room_tv
    #   data:
    #     message: "The sun will set in 55 mins. Turning on all lights."

# Turn off lights at 23:45
- alias: "Lights off at 23:45 (sun-thu)"
  trigger:
    - platform: time
      after: "23:45"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_window_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_ball_lights

# Dim lights at 20:00 for night mode
- alias: "Dim lights to night mode at 20:00"
  trigger:
    - platform: time
      after: "20:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_hue
          - light.living_room_hue
        brightness: 100
        color_temp: 410
        transition: 2
    - service: light.turn_on
      data:
        entity_id:
          - light.kids_room
        brightness: 100
        rgb_color: [255, 68, 0]
        transition: 2

# Turn off kids room lights at 21:00
- alias: "Kids room lights off at 21:00"
  trigger:
    - platform: time
      after: "21:00"
  action:
    - service: light.turn_off
      entity_id: light.kids_room

# Turn on Main PC when Georgi comes home
- alias: "Turn on main PC when Georgi comes home"
  trigger:
    - platform: state
      entity_id: device_tracker.georgi6p_gp
      state: 'home'
  condition:
    - condition: time
      after: '16:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.main_computer