# Turn on lights at sunset
- alias: "Lights on at sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    - service: homeassistant.turn_on
      entity_id: group.all_lights
    - service: tts.google_say
      entity_id: media_player.living_room_tv
      data:
        message: "The sun will set in 45 minutes. Turning on all lights."