# Turn on lights at sunset
- alias: "Lights on 30 mins before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_hue
          - light.living_room_hue
          - light.antons_room
          - light.kitchen
        brightness: 225
        color_temp: 327
        transition: 5
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Sunset in half an hour. Turning on all lights."

# Turn off lights at 23:45
- alias: "Lights off at 23:45 (sun-thu)"
  trigger:
    - platform: time
      at: "23:45"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.office_hue
          - light.living_room_hue
          - light.kitchen
        transition: 5
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_window_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_ball_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_charger

# SUMMER: Dim lights at 20:00 for night mode
- alias: "Dim lights to night mode at 20:00"
  trigger:
    - platform: time
      at: "20:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_hue
          - light.living_room_hue
          - light.antons_room
          - light.kitchen
        brightness: 100
        color_temp: 410
        transition: 5
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "It is now 8pm. Setting the house to night mode."

# Turn off Anton's room lights at 20:30
- alias: "Anton's room lights off at 20:30"
  trigger:
    - platform: time
      at: "20:30"
  action:
    - service: light.turn_off
      entity_id: light.antons_room

# LUX SENSOR BASED AUTOMATIONS
# Turn on office light based on LUX sensor
- alias: "Turn on office light based on LUX sensor"
  trigger:
    platform: numeric_state
    entity_id: sensor.sn1_ldr
    below: 10
  condition:
    - condition: state
      entity_id: light.office_hue
      state: "off"
    - condition: time
      after: "07:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.office_hue
        brightness: 225
        color_temp: 327
        transition: 5

# Turn off office light based on LUX sensor
- alias: "Turn off office light based on LUX sensor"
  trigger:
    platform: numeric_state
    entity_id: sensor.sn1_ldr
    above: 25
  condition:
    - condition: state
      entity_id: light.office_hue
      state: "on"
    - condition: time
      after: "07:00"
  action:
    - service: homeassistant.turn_off
      entity_id: light.office_hue

# Turn on living room light based on LUX sensor
- alias: "Turn on living room light based on LUX sensor"
  trigger:
    platform: numeric_state
    entity_id: sensor.sn2_ldr
    below: 10
  condition:
    - condition: state
      entity_id: light.living_room_hue
      state: "off"
    - condition: time
      after: "07:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.living_room_hue
        brightness: 225
        color_temp: 327
        transition: 5

# Turn off living room light based on LUX sensor
- alias: "Turn off living room light based on LUX sensor"
  trigger:
    platform: numeric_state
    entity_id: sensor.sn2_ldr
    above: 25
  condition:
    - condition: state
      entity_id: light.living_room_hue
      state: "on"
    - condition: time
      after: "07:00"
  action:
    - service: homeassistant.turn_off
      entity_id: light.living_room_hue

# Office ws2812b led strip
- alias: "Office Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_number.office_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "home/office/led_strip/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'

# Office ws2812b led strip
- alias: "Livingroom Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_number.livingroom_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "home/livingroom/led_strip/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'

# Turn on morning lights before work at 6:50
- alias: Turn on morning lights before work at 6:50
  trigger:
    - platform: time
      at: "06:50"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_hue
          - light.kitchen
        brightness: 200
        color_temp: 300
        transition: 50
    - delay: 00:20:00
    - service: light.turn_off
      entity_id:
        - light.office_hue
        - light.kitchen