# Turn on lights at sunset
- alias: "Lights on 2 hours before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-02:00:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.living_room_hue
          - light.office_hue
        brightness: 225
        color_temp: 327
        transition: 2
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_window_lights
    - service: homeassistant.turn_on
      entity_id: switch.livingroom_ball_lights
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.kids_room
          - light.kitchen
        brightness: 225
        color_temp: 240
        rgb_color: [255, 250, 202]
        transition: 2
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Sunset in 2 hours. Turning on all lights."

# Turn off lights at 23:45
- alias: "Lights off at 23:45 (sun-thu)"
  trigger:
    - platform: time
      after: "23:45"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_window_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_ball_lights
    - service: homeassistant.turn_off
      entity_id: switch.livingroom_charger

# Dim lights at 20:00 for night mode
- alias: "Dim lights to night mode at 20:00"
  trigger:
    - platform: time
      after: "20:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_hue
          - light.living_room_hue
          - light.kids_room
          - light.kitchen
        brightness: 100
        color_temp: 410
        transition: 2
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "It is now 8pm. Setting the house to night mode."

# Turn off kids room lights at 21:00
- alias: "Kids room lights off at 21:00"
  trigger:
    - platform: time
      at: "21:00"
  action:
    - service: light.turn_off
      entity_id: light.kids_room

# LUX SENSOR BASED AUTOMATIONS
# Turn on office light based on LUX sensor
- alias: "Turn on office light based on LUX sensor"
  trigger:
    platform: numeric_state
    entity_id: sensor.sn1_ldr
    below: 10
  condition:
    - condition: state
      entity_id: light.office_hue
      state: "off"
    - condition: time
      after: "07:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.office_hue
        brightness: 225
        color_temp: 327
        transition: 5

# Turn on living room light based on LUX sensor
- alias: "Turn on living room light based on LUX sensor"
  trigger:
    platform: numeric_state
    entity_id: sensor.sn2_ldr
    below: 10
  condition:
    - condition: state
      entity_id: light.living_room_hue
      state: "off"
    - condition: time
      after: "07:00"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.living_room_hue
        brightness: 225
        color_temp: 327
        transition: 5

# Porch ws2812b led strip
- alias: "Porch Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_slider.porch_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "home/porch/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'