- alias: "ManyThing Recording ON"
# This calls an IFTTT recipe to turn on recording of the ManyThing Camera
# if we leave the house during the day.
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.manything_status
    state: "turn_on"
  action:
    service: ifttt.trigger
    data: {"event":"manything_on"}