- alias: "ManyThing Recording OFF"
# This calls an IFTTT recipe to turn off recording of the ManyThing Camera
# when we are home unless it's nighttime.
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.manything_status
    state: "turn_off"
  action:
    service: ifttt.trigger
    data: {"event":"manything_off"}